source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DZScene_Example', :exclusive => true do
  pod 'DZScene', :path => '../'
end

target 'DZScene_Tests', :exclusive => true do
  pod 'DZScene', :path => '../'

  pod 'FBSnapshotTestCase'
end
